### ISSUE TITLE
Why is the directory package explicit?

### ISSUE THREAD

**Issue by eklavya** [jfdm/smokehill#1]
Hi,

I was trying to get intero setup. It was failing because of the explicit directory package.

In stack.yaml:
```yaml
directory-1.2.6.3
```

I removed that line and smokehill still compiles but also intero works now. Is there a particular reason it's explicit instead of letting stack decide based on the LTS and the dependencies? If it is removed, it will be good for ide setup (for intero).

**Comment by jfdm** [comment]
It appears to be technical debt. When I first wrote the code, there were problems with the versions of `directory` used in LTS. I suppose I can revisit the dependancies in the near future.

**Comment by jfdm** [comment]
I've updated the stack config, and can close the issue.
